openapi: 3.0.0
info:
  title: Deprecated API
  version: 1.0.0
servers:
  - url: https://api.example.com
    description: production
paths:
  /deprecated:
    get:
      summary: Deprecated summary
      operationId: getDeprecated
      deprecated: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
