openapi: 3.0.0
info:
  title: Multi-Server API
  version: 1.0.0
servers:
  - url: https://api.production.com
    description: Production server
  - url: https://api.development.com
    description: Development server
paths:
  /test:
    post:
      summary: Create a test resource
      operationId: createTest
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
